### ISSUE TITLE
Core allocation in MANTIS

### ISSUE THREAD

**Issue by susheelbhanu** [PedroMTQ/mantis#10]
Hey @PedroMTQ, 

I'm running MANTIS via `snakemake` with the following command: `snakemake -s Snakefile --use-conda --cores 64 -rp`

The log file, however, states the `112 cores were allocated`
```
#  This MANTIS process started running at 2021-04-28 23:23:51
Cores allocated: 112
Memory allocated: 967.37
Workers per core: 1
```

Is there a flag to `limit the number of cores it uses?

Thank you!

**Comment by PedroMTQ** [comment]
Hello @susheelbhanu 
Yes, you can use `-c` for the number of cores. For further details on execution parameters see https://github.com/PedroMTQ/mantis/wiki/Functionalities#annotate-one-sample

Regards,
Pedro
