### ISSUE TITLE
Add translation of CDS

### ISSUE THREAD

**Issue by PedroMTQ** [PedroMTQ/mantis#11]
Allow for the input of CDS besides protein sequences

**Comment by xiekunwhy** [comment]
Hi,

Any progress? I want to use mantis to annotate a non-model species transciptome sequences.

Best,
Kun

**Comment by PedroMTQ** [comment]
Currently working on it, it should be ready within this/next week.

Regards,
Pedro

**Comment by PedroMTQ** [comment]
This is now implemented, Mantis will now check sample type (RNA,DNA, or protein) and translate accordingly. Keep in mind this is a simple translation so CDS should still be provided if translating.

This will be released in the next update.
