### ISSUE TITLE
merge_hmm_folder not work normally.

### ISSUE THREAD

**Issue by xiekunwhy** [PedroMTQ/mantis#15]
Hi,

setup_databases still need to run long long time. So I was downloaded eggnog hmm files and tried to use merge_hmm_folder to merge hmm files, but it didn't worked normally, do you why?
Here are the hmm files
ls 548681/|head
4R16V.hmm
4R16W.hmm
4R16X.hmm
4R16Y.hmm
4R16Z.hmm
4R170.hmm
4R171.hmm
4R172.hmm
4R173.hmm
4R174.hmm
python /state/partition1/WORK/Bio/Project/xiek/software/mantis/ merge_hmm_folder -t 548681/

Here are the error logs
  Weights: nog:0.8, pfam:0.9, tigrfam:0.5

  Merging hmm folder:
548681/
Merging hmm folder: 548681/
[: missing `]'
Traceback (most recent call last):
  File "/Bio/User/kxie/software/anaconda3/envs/mantis/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Bio/User/kxie/software/anaconda3/envs/mantis/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/state/partition1/WORK/Bio/Project/xiek/software/mantis/__main__.py", line 187, in <module>
    merge_hmm_folder(target_folder=target)
  File "/state/partition1/WORK/Bio/Project/xiek/software/mantis/source/MANTIS_Assembler.py", line 31, in merge_hmm_folder
    mantis.merge_hmm_folder(target_folder)
  File "/state/partition1/WORK/Bio/Project/xiek/software/mantis/source/MANTIS_Assembler.py", line 335, in merge_hmm_folder
    run_command(
  File "/state/partition1/WORK/Bio/Project/xiek/software/mantis/source/utils.py", line 942, in run_command
    return run_command_simple(command=command_list, get_output=get_output, stdout_file=stdout_file)
  File "/state/partition1/WORK/Bio/Project/xiek/software/mantis/source/utils.py", line 740, in run_command_simple
    process = subprocess.run(command)
  File "/Bio/User/kxie/software/anaconda3/envs/mantis/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Bio/User/kxie/software/anaconda3/envs/mantis/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Bio/User/kxie/software/anaconda3/envs/mantis/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'for'

Best,
Kun

**Comment by PedroMTQ** [comment]
Hi Kun,

I will check the merge_hmm_folder function but it seems to be a permission issue? Do you have permission to write on the particular folder?
Also why are you running merge_hmm_folder for the eggnog hmms? Why not setup_databases?
When you ran merge_hmm_folder did you try using -t with the absolute path?

**Comment by xiekunwhy** [comment]
Hi @PedroMTQ 
> I will check the merge_hmm_folder function but it seems to be a permission issue? Do you have permission to write on the particular folder?

Yes, I have permission to write on the folder where 548681 in.

> Also why are you running merge_hmm_folder for the eggnog hmms? Why not setup_databases?

There are still many zombie jobs, and setup_databases work very slow.

> When you ran merge_hmm_folder did you try using -t with the absolute path?

I have tried python /state/partition1/WORK/Bio/Project/xiek/software/mantis/ merge_hmm_folder -t /state/partition1/WORK/Bio/Project/xiek/pipe/annot/eggnog/hmms_merge/548681/548681, but got the same error.

Best,
Kun

**Comment by PedroMTQ** [comment]
Hello,
How long has setup_databases been running for? I ran it several times and it took 2-3 days to setup with all the data (if using the eggNOG database). I could not replicate the zombie processes issue on my end, as all spawned processes seem to terminate once the setup queue is empty...
Could you please check the mantis/setup_databases/Mantis.out file? It should tell you which step it is currently on in more detail (besides the usual console log).

Also, are you only interested in that particular taxa i.e., 548681? If so, you could limit the download to that taxa instead of downloading the whole eggNOG database.

**Comment by PedroMTQ** [comment]
Also, how many cores are you using for the setup? I generally run it with 20ish cores for the aforementioned timeframe

**Comment by xiekunwhy** [comment]
Hi @PedroMTQ 

16 cores I was used, and setup_databases is running 4 days now. I need to tell you that the national firewall in China is difference from other countries, some websites (including ncbi and eggnog) can not accessed in the default way. That's why I need to dowload them myself.

I think there is aserious bug in printing mantis/setup_databases/Mantis.out when the network is abnormal, the size of this file is now ~12Gb and still growing, the most infomation in this file is about NCBI.

I think I need to kill setup_databases now.

wc -l Mantis.out 
377680267 Mantis.out

head -30 Mantis.out
Tax 10404 hmm and annotations.tsv files already exist, and they were merged correctly. Skipping setup...
Tax 10474 hmm and annotations.tsv files already exist, and they were merged correctly. Skipping setup...
Tax 10477 hmm and annotations.tsv files already exist, and they were merged correctly. Skipping setup...
Tax 10656 hmm and annotations.tsv files already exist, and they were merged correctly. Skipping setup...
Tax 10841 hmm and annotations.tsv files already exist, and they were merged correctly. Skipping setup...
Tax 10860 hmm and annotations.tsv files already exist, and they were merged correctly. Skipping setup...
Tax 11157 hmm and annotations.tsv files already exist, and they were merged correctly. Skipping setup...
Will compile data for the following NOGT:
10,1016,10239,1028384,104264,1060,10662,10699,10744,1090,1100069,110618,1117,112252,1129,1142,1150,1161,11632,1164882,117743,117747,118882,118884,1189,118969,119043,119045,119060,119065,119066,119069,119089,119603,11989,121069,1212,122277,1224,1236,1239,1268,1283313,129337,1297,1303,1305,1307,1313,135613,135614,135618,135619,135623,135624,135625,1357,136841,136843,136845,136846,136849,1386,142182,145357,147541,147545,147548,147550,150247,1506553,1511857,155619,1570339,157897,1653,167375,171550,171551,1762,178469,182709,183925,183939,183963,183967,183968,183980,186801,186804,186806,186807,186813,186818,186820,186821,186822,186823,186824,186827,186828,186928,189330,189775,191028,191675,2,200643,200783,200795,200918,200930,200940,201174,203494,203682,203691,204037,204428,204432,204441,204457,204458,2063,206350,206351,206389,213113,213115,213118,213462,213481,2157,216572,224756,225057,228398,2323,237,2433,244698,245186,246874,252301,252356,255475,256005,265,265975,267888,267889,267890,267893,267894,2759,28037,28211,28216,28221,2836,283735,285107,28883,28889,28890,289201,29,29000,290174,29258,29547,301297,302485,3041,308865,311790,314146,314294,31979,31993,32003,32061,32066,32199,326319,326457,33090,33154,33183,33208,33213,33342,33554,335928,33867,33958,34008,34037,34383,34384,34397,35237,35268,35278,35301,35325,35493,355688,35718,358033,363408,3699,38820,39782,400634,40117,40674,41294,414999,422676,423358,439488,43988,4447,451866,451867,451870,452284,45401,45404,45667,46205,464095,468,4751,4776,4890,4891,4893,5042,50557,506,508458,5125,5129,5139,5148,5151,52018,5204,5234,52604,526524,52959,53335,5338,53433,538999,539002,541000,544,544448,547,548681,551,554915,558415,561,5653,572511,57723,5794,5796,5809,5819,583,586,5863,5878,58840,590,59732,60136,613,61432,622450,6231,6236,629,629295,639021,651137,6656,671232,675063,68295,68298,68525,68892,69277,69541,69657,7088,71274,713636,7147,7148,7214,72273,72275,7399,74030,74201,74385,75682,766,766764,76804,76831,768503,7711,772,7742,7898,80864,815,81850,81852,82115,82117,82986,830,83612,84406,8459,84992,84995,84998,85004,85005,85008,85009,85010,85012,85013,85014,85016,85017,85018,85019,85020,85021,85023,85025,85026,8782,90964,909932,91061,91561,91835,9263,92860,93682,9397,9443,9604,97050,976,995019,9989
NCBI taxonomic lineage file already exists! Skipping...
Finished downloading ncbi_res
Pfam hmm already exists! Skipping...
Finished downloading pfam
KOfam HMM already exists! Skipping...
Finished downloading kofam
TIGRfam hmm already exists! Skipping...
Finished downloading tigrfam
NCBI hmm folder already exists! Skipping...
Finished downloading NCBI
Setup failed on NCBI None
NCBI hmm folder already exists! Skipping...
Finished downloading NCBI
Setup failed on NCBI None
NCBI hmm folder already exists! Skipping...
Finished downloading NCBI
Setup failed on NCBI None
NCBI hmm folder already exists! Skipping...
Finished downloading NCBI
Setup failed on NCBI None
NCBI hmm folder already exists! Skipping...

tail -30 Mantis.out
Setup failed on NCBI None
NCBI hmm folder already exists! Skipping...
Finished downloading NCBI
Setup failed on NCBI None
NCBI hmm folder already exists! Skipping...
Finished downloading NCBI
Setup failed on NCBI None
NCBI hmm folder already exists! Skipping...
Finished downloading NCBI
Setup failed on NCBI None
NCBI hmm folder already exists! Skipping...
Finished downloading NCBI
Setup failed on NCBI None
NCBI hmm folder already exists! Skipping...
Finished downloading NCBI
Setup failed on NCBI None
NCBI hmm folder already exists! Skipping...
Finished downloading NCBI
Setup failed on NCBI None
NCBI hmm folder already exists! Skipping...
Finished downloading NCBI
Setup failed on NCBI None
NCBI hmm folder already exists! Skipping...
Finished downloading NCBI
Setup failed on NCBI None
NCBI hmm folder already exists! Skipping...
Finished downloading NCBI
Setup failed on NCBI None
NCBI hmm folder already exists! Skipping...
Finished downloading NCBI

Best,
Kun

**Comment by PedroMTQ** [comment]
Hello,
> 16 cores I was used, and setup_databases is running 4 days now. I need to tell you that the national firewall in China is difference from other countries, some websites (including ncbi and eggnog) can not accessed in the default way. That's why I need to dowload them myself.

This might complicate things. Perhaps you could share how you did it so other users can replicate your solution if faced with the same issue (if it's nothing major I could maybe also add a workaround)?
Yes, it seems like it's stuck downloading NCBI, could you kill it now? Did it download anything into the NCBI hmm folder?
Please update your repo and try again, I've added a new checking system so it doesn't get stuck there. 

Regarding the merge_hmm_folder, indeed it seems some Python update broke it. I've fixed it.

**Comment by xiekunwhy** [comment]
Hi

Things almost done. I was killed the jobs and do it follow these steps
1) Delete mantis/References/NCBI folder;
2) Download eggnog hmm.tar.gz and annotations.tsv.gz files myself and then copy them to the correspoding folders (mantis/References/NOG/*/);
3) Run setup_databases again, hmm and taxa information files from NCBI were downloaded normally this time. And mantis didn't need to download files from eggnog database, just Gunzipping Merging Concatenating and indexing the files I have downloaded. So it worked through.

I found a new bug when I ran check_installation, the check_installation module check **taxa_sql_annotations.tsv** file insteed of **taxa_annotations.tsv**, for example, Failed installation check on [files missing]: /state/partition1/WORK/Bio/Project/xiek/software/mantis/References/NOG/135625/
135625_sql_annotations.tsv

but 135625_annotations.tsv was already there.

ls /state/partition1/WORK/Bio/Project/xiek/software/mantis/References/NOG/135625/|cat
135625_annotations.tsv
135625_annotations.tsv.gz
135625_merged.hmm
135625_merged.hmm.h3f
135625_merged.hmm.h3i
135625_merged.hmm.h3m
135625_merged.hmm.h3p

Best,
Kun

**Comment by PedroMTQ** [comment]
Hello,
I'm glad to hear you are almost there.
That is not a bug, the **taxa_annotations.tsv** is the file downloaded from eggNOG but it does not contain all the necessary metadata. So we compiled and distribute a **taxa_sql_annotations.tsv** which contains all the metadata from each sequence in the respective HMM.
The **taxa_sql_annotations.tsv** are unpacked during setup_databases.

Regards,
Pedro

**Comment by xiekunwhy** [comment]
Hi,

I see, setup_databases finished normally.

An other question, I can't find any document about -ar acceptable_range option when running python mantis/ run_mantis -h, also not found in wiki page, -ar is a new option?

Best,
Kun

**Comment by PedroMTQ** [comment]
Hello,
Glad you managed. 
acceptable_range is a legacy variable, I forgot to remove it from the wiki!

Regards,
Pedro
