### ISSUE TITLE
Source of pfam metadata

### ISSUE THREAD

**Issue by xiekunwhy** [PedroMTQ/mantis#17]
Hi,

Sorry to trouble you again.

And I want to know where the source of pfam metadata come from, it seems that not all GO terms in the metadata.tsv match those in http://current.geneontology.org/ontology/external2go/pfam2go file.

Best,
Kun

**Comment by PedroMTQ** [comment]
Hello @xiekunwhy,

You are absolutely correct, I missed the fact that a Pfam accession can show up more than once in that list. I've now fixed it.
To apply the fix please set all references to NA except Pfam in the config file, then delete the current Pfam metadata.tsv and run `setup_databases`. After this is complete revert the config to its previous state. The metadata.tsv should now be fixed.

Thanks for noticing and regards,
Pedro

**Comment by xiekunwhy** [comment]
Hi,

Things OK now.

A suggestion, users can do annotation more efficiently if mantis can accept hmmsearch results as input when there are huge query sequences. Because hmmsearch can be run independently using multiple computer nodes on a cluster. Like eggnog-mapper does (https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.1.2#Setting_up_large_annotation_jobs).

Best,
Kun

**Comment by PedroMTQ** [comment]
Hi @xiekunwhy 
Indeed, interaction between multiple physical computer could be of benefit. We decided not to implement something like the aforementioned method as it would require some significant changes in Mantis' architecture. But this is something we may consider adding further down the line.
In the meantime the user can still split their sample and run multiple Mantis' instances instead and then merge the results.

I will add your suggestion as an enhancement issue.

Regards,
Pedro
