### ISSUE TITLE
Will * in protein sequence affect results?

### ISSUE THREAD

**Issue by xiekunwhy** [PedroMTQ/mantis#19]
Hi,

I use six-frame translated sequences as input. But I found that many * symbl in translated sequences, will these * affect results?
HMMER doesn't particularly like * characters according to https://github.com/EddyRivasLab/hmmer/issues/205.

Best,
Kun

Many translated sequences like followings 
[unigene_faa.txt](https://github.com/PedroMTQ/mantis/files/6562049/unigene_faa.txt)

**Comment by PedroMTQ** [comment]
Hi,
I didn't implement any special rule to deal with *, so I would probably remove the * as suggested by HMMER's developer.

Regards,
Pedro
