### ISSUE TITLE
Not able to make work the "master" branch

### ISSUE THREAD

**Issue by Cantalapiedra** [PedroMTQ/mantis#3]
Hi,

I am trying to setup the software.
When I clone the repo from the master branch I got a Resouces/NOG_sql.tar.gz which is a text file with the next content:

version https://git-lfs.github.com/spec/v1
oid sha256:cecd31773a7cc729723d298b158d6cdc98187a143de2255095e73cb81f1ea394
size 176132348

When I use the setup or the check command, I got errors, apparently because of this:

raceback (most recent call last):
  File "miniconda3/envs/mantis_env/lib/python3.8/shutil.py", line 1155, in _unpack_tarfile
    tarobj = tarfile.open(filename)
  File "miniconda3/envs/mantis_env/lib/python3.8/tarfile.py", line 1606, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "miniconda3/envs/mantis_env/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "miniconda3/envs/mantis_env/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "mantis/__main__.py", line 114, in <module>
    setup_databases(force_download=force_download,chunk_size=chunk_size,mantis_config=mantis_config)
  File "mantis/source/MANTIS_Assembler.py", line 28, in setup_databases
    mantis.setup_databases(force_download)
  File "mantis/source/utils.py", line 417, in wrapper
    res = f(self,*args, **kwargs)
  File "mantis/source/MANTIS_DB.py", line 57, in setup_databases
    self.prepare_queue_extract_metadata()
  File "mantis/source/MANTIS_DB.py", line 97, in prepare_queue_extract_metadata
    self.unpack_NOG_sql(stdout_file=stdout_file)
  File "mantis/source/MANTIS_DB.py", line 430, in unpack_NOG_sql
    uncompress_archive(source_filepath=NOG_sql_path,extract_path=resources_path,stdout_file=stdout_file,remove_source=False)
  File "mantis/source/utils.py", line 428, in uncompress_archive
    unpack_archive(source_file=source_filepath, extract_dir=extract_path, remove_source=remove_source, stdout_file=None)
  File "mantis/source/utils.py", line 458, in unpack_archive
    shutil.unpack_archive(source_file,extract_dir=extract_dir)
  File "miniconda3/envs/mantis_env/lib/python3.8/shutil.py", line 1227, in unpack_archive
    func(filename, extract_dir, **kwargs)
  File "miniconda3/envs/mantis_env/lib/python3.8/shutil.py", line 1157, in _unpack_tarfile
    raise ReadError(
shutil.ReadError: mantis/mantis/Resources/NOG_sql.tar.gz is not a compressed or uncompressed tar file

I first thought that Resources/NOG_sql/ would contain the data of NOG_sql.tar.gz, so I removed NOG_sql.tar.gz and created it again using NOG_sql. However, doing this I am getting:

Traceback (most recent call last):
  File "miniconda3/envs/mantis_env/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "miniconda3/envs/mantis_env/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "mantis/__main__.py", line 114, in <module>
    setup_databases(force_download=force_download,chunk_size=chunk_size,mantis_config=mantis_config)
  File "mantis/source/MANTIS_Assembler.py", line 28, in setup_databases
    mantis.setup_databases(force_download)
  File "mantis/source/utils.py", line 417, in wrapper
    res = f(self,*args, **kwargs)
  File "mantis/source/MANTIS_DB.py", line 57, in setup_databases
    self.prepare_queue_extract_metadata()
  File "mantis/source/MANTIS_DB.py", line 97, in prepare_queue_extract_metadata
    self.unpack_NOG_sql(stdout_file=stdout_file)
  File "mantis/source/MANTIS_DB.py", line 434, in unpack_NOG_sql
    for f in os.listdir(NOGG_sql_path):
FileNotFoundError: [Errno 2] No such file or directory: 'mantis/mantis/Resources/NOG_sql/NOGG/'

Therefore, I guess that both NOG_sql and NOG_sql.tar.gz are required and contain different data??

Best,
Carlos

**Comment by PedroMTQ** [comment]
Hello Carlos,
Another user had the same issue. This is an issue with git not correctly downloading large files (NOG_sql.tar.gz). I'm now releasing a v1.01 where this issue (among a few other minor improvements) is addressed. 
Could you please reclone the repo and try again?

**Comment by Cantalapiedra** [comment]
Hi @PedroMTQ ,

OK, I already cloned it and will try again.

I am struggling a bit, because in the server I am trying to install Mantis because it cannot download the FTP databases (likely due to port 21 being closed in the server, not sure). Therefore, I yet have to clone and install only the FTP databases in a local computer, then clone and install the NOG databases in the server (I have no space for this in the local computer), then copy the FTP local databases to the server. If you can figure out an easier way to do this advice is welcome :)

Anyway, I will report back once that I have tried the setup_databases with the 1.01 cloned version in the local computer.

Thanks,
Carlos

**Comment by PedroMTQ** [comment]
Hi again,
Depending on the analysis you are planning to do, I might have a few suggestions.
But the first thing I can think of is: if you are not using taxonomically classified samples, we could restrict the reference datasets to all the default ones besides the NOGT ( taxa specific eggNOG).
That should be feasible to download on your local computer and then transfer to the server.
To do so please pull the repo again (I just added some code to allow you to do that) and edit the MANTIS.config so that only the NOGT data is not used. You can do this by using this config file:

```
NOGT_hmm_folder=NA
NOGG_weight=0.8
pfam_weight=0.9
tigrfam_weight=0.5
```

This will skip NOGT download during the setup but download all the rest reference data.
If your samples are taxonomically classified, I'm not entirely sure what the solution would if you can't download this data in your server. But we could potentially think of something that would suit your needs. Perhaps you could explain a bit better why the server is not downloading anything?

**Comment by Cantalapiedra** [comment]
Hi @PedroMTQ ,

My plan was to use the taxonomy databases also. 
The server is downloading the NOGT and NOGG databases fine, I think. The problem is with the ones from FTP servers (pfam, kofam, and tigrfam).
I was actually trying something similar to what you advice above, but still using snapshot afa47e3.

Locally, I ran the setup_databases with config like:

NOGT_hmm_folder=NA
NOGG_hmm_folder=NA

So that I should have the pfam, kofam and tigrfam databases locally, hopefully.

In the server:

pfam_hmm_folder=NA
kofam_hmm_folder=NA
tigrfam_hmm_folder=NA

My plan was then to copy the pfam, kofam, and tigrfam directories under mantis/hmm to the one on the server, so that I will have finally all of the together. Would this work? What did you changed in the last commit? I guess I can pull after the setup databases process? because it is currently unpacking the NOGTs which takes a while, so I would love to don't need to do it again. If I need to do it, I will though.

Thanks for you help.

Carlos

**Comment by PedroMTQ** [comment]
Ah, I see. yes that way should work fine!
Actually, by mistake I introduced a bug in file concatenation (used during database setup) in that version. Sorry for the trouble.
So, could you pull the new repository locally and in the server and then restart the setup?

**Comment by Cantalapiedra** [comment]
Hi @PedroMTQ ,

what do you mean with restarting the setup? Should I remove any files from the previous setup first? or just pull followed by setup_databases in both local and server?

Thank you again.

**Comment by PedroMTQ** [comment]
Hello,
I mean removing the old files, pulling from the repo or just cloning again and restarting the setup.
Hopefully it won't take too long! Sorry for the trouble!

**Comment by Cantalapiedra** [comment]
ok! No problem! Thank you

**Comment by PedroMTQ** [comment]
Great, let me know how it goes!

**Comment by Cantalapiedra** [comment]
Hi,

so I created a third repo clone, to run setup_databases without databases (just in case), and then linked the databases from the server setup (NOGG, NOGT) and to the local setup (kofam, pfam, tigrfam).

Everything seems to be running fine now.

Thank you very much.

Best,
Carlos
