### ISSUE TITLE
GFF output for the annotation

### ISSUE THREAD

**Issue by Mass23** [PedroMTQ/mantis#30]
Dear Pedro,

I was wondering if there was a possibility to output the results in a GFF instead of the .tsv files for the consensus annotation? 

Best regards,

Massimo

**Comment by PedroMTQ** [comment]
Hello Massimo, 
Yes sure. I'll be somewhat busy this week but I'll try to work on it and add this option next week. I will keep you posted.

Regards,
Pedro

**Comment by Mass23** [comment]
Dear Pedro,

Thank you very much! Let me know if I can be of any help to code/test it!

Best,

Massimo

**Comment by PedroMTQ** [comment]
Hello Massimo,

I'm done adding the GFF output (`-gff` when running Mantis).
output verified with: http://genometools.org/cgi-bin/gff3validator.cgi
output formatted according to gff v3: https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md

I tested this a few times so it should work fine but please let me know if you run into any issues.

Regards,
Pedro
