### ISSUE TITLE
Potentially wrong GFF format

### ISSUE THREAD

**Issue by VGalata** [PedroMTQ/mantis#35]
Hey @PedroMTQ,

I think that the GFF format of the output files is not completely correct (which I have unfortunately not noticed before):

- the sequence-regions in the header should be contig IDs and not IDs of the features
- the 1st column ("seqid") should contain the contig ID and not the feature ID
- the 9th column ("attributes") should contain the feature ID, i.e. `ID=<feature ID>;...`

For reference: [GFF3 format convention](https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md)

Could you have a look at this?

**Comment by PedroMTQ** [comment]
Hello Valentina,
Indeed, the GFF is not per contig but per sequence.
I'll add a note to the wiki mentioning this.

Regards,
Pedro
