### ISSUE TITLE
Issue with Mantis Setup

### ISSUE THREAD

**Issue by jblakele** [PedroMTQ/mantis#44]
Hi,

I am trying to install mantis on my labs server. The conda install went fine but the setup step did not work. Could you help me with this? 

I run: mantis setup

Then get the following string of text. It looks like it's getting hung up at the downloading eggNOG step. I was able to download eggnog.db.gz separately, none of the other references were downloaded. Is it possible to set this up outside of setup or is it a bug?

I appreciate the help,
Alfredo 

Executing command:
 /tools/miniconda3/envs/MANTIS-Annotation/bin/mantis setup -c 20 -m 100
#  Setting up databases
ESC[32mUsing default MANTIS.cfg: /tools/miniconda3/envs/MANTIS-Annotation/lib/python3.9/site-packages/config/MANTIS.cfgESC[0m
Default references folder:
/tools/miniconda3/envs/MANTIS-Annotation/lib/python3.9/site-packages/References/
Resources folder:
/tools/miniconda3/envs/MANTIS-Annotation/lib/python3.9/site-packages/Resources/
Custom references folder:
/tools/miniconda3/envs/MANTIS-Annotation/lib/python3.9/site-packages/References/Custom_references/
TAX NOG references folder:
/tools/miniconda3/envs/MANTIS-Annotation/lib/python3.9/site-packages/References/NOG/
TAX NCBI references folder:
/tools/miniconda3/envs/MANTIS-Annotation/lib/python3.9/site-packages/References/NCBI/
Pfam reference folder:
/tools/miniconda3/envs/MANTIS-Annotation/lib/python3.9/site-packages/References/pfam/
KOfam reference folder:
/tools/miniconda3/envs/MANTIS-Annotation/lib/python3.9/site-packages/References/kofam/
TCDB reference folder:
/tools/miniconda3/envs/MANTIS-Annotation/lib/python3.9/site-packages/References/tcdb/
------------------------------------------#  Weights:
nog:0.8, pfam:0.9

Will check data for the following NOGT:
995019,119603,7147,526524,1506553,68525,91061,228398,200643,1313,147541,1303,11632,2836,506,203682,33958,59732,118969,1100069,9397,651137,33154,50557,97050,81852,11989,38820,1164882,167375,85018,58840,69657,1307,119060,135625,200940,206389,713636,33183,400634,35301,40674,7148,40117,85016,766,11157,5125,186822,155619,135614,204458,1129,53335,29,85008,1268,183925,4890,72273,186807,33554,119089,1090,583,183963,267888,28211,10239,8782,265,35268,10699,46205,213118,204457,157897,117743,976,9989,90964,267893,7399,85012,586,91835,2,135624,68298,135618,326319,8459,10,285107,544448,5042,548681,119043,572511,314146,772,7711,76831,561,72275,5878,52959,671232,6231,1297,33342,186928,5863,200930,213481,1212,43988,7898,28221,81850,439488,85019,136846,265975,225057,121069,29000,267890,136845,7214,200918,5653,5148,204441,3699,85026,363408,186827,35237,85004,34397,4776,28890,85013,150247,237,35278,186828,622450,1,34383,33208,203494,85021,267889,35325,2433,766764,119065,191028,7088,186821,85005,110618,4891,45404,61432,10656,204428,28216,355688,68892,539002,112252,302485,1142,1570339,10841,57723,1239,10404,186813,186824,311790,76804,33090,290174,183967,68295,267894,35493,189330,244698,45401,60136,541000,45667,245186,1386,256005,224756,118884,213115,4751,75682,508458,1762,142182,33213,201174,186804,5151,2063,84998,451870,629,147548,85010,206350,283735,301297,613,5204,830,71274,675063,1060,186823,558415,1357,135613,252356,118882,203691,32061,289201,547,544,1236,85017,10860,136849,186820,171551,41294,909932,84406,213113,1653,136843,119069,6236,85020,7742,252301,32199,93682,6656,246874,135623,414999,1305,216572,551,2157,34037,422676,5338,74030,69277,136841,213462,468,186818,451867,5819,1511857,768503,117747,84992,92860,538999,31979,326457,74385,53433,85014,83612,206351,85009,815,1161,85025,186801,255475,183980,5794,82986,639021,34384,29258,4893,84995,2759,32003,2323,28883,91561,104264,147550,189775,191675,464095,82117,629295,1117,200795,1189,5796,10474,9263,80864,314294,423358,1150,52604,1016,358033,135619,451866,5809,119066,39782,85023,74201,308865,171550,10744,5234,4447,204037,33867,28037,5139,590,1283313,186806,29547,145357,554915,183939,147545,5129,452284,335928,10662,3041,9443,122277,129337,182709,200783,32066,1028384,31993,119045,69541,28889,35718,9604,34008,82115,10477,1224,183968,178469,204432,52018
/tools/miniconda3/envs/MANTIS-Annotation/lib/python3.9/site-packages/References/NOG/eggnog.db.gz
Downloading from http://eggnogdb.embl.de/download/emapperdb-5.0.2/eggnog.db.gz. The file will be kept in /tools/miniconda3/envs/MANTIS-Annotation/lib/python3.9/site-packages/References/NOG/
Did not manage to download the following url correctly:
http://eggnogdb.embl.de/download/emapperdb-5.0.2/eggnog.db.gz
Traceback (most recent call last):
  File "/tools/miniconda3/envs/MANTIS-Annotation/bin/mantis", line 11, in <module>
    sys.exit(main())
  File "/tools/miniconda3/envs/MANTIS-Annotation/lib/python3.9/site-packages/mantis/__main__.py", line 184, in main
    setup_databases(chunk_size=chunk_size, no_taxonomy=no_taxonomy,
  File "/tools/miniconda3/envs/MANTIS-Annotation/lib/python3.9/site-packages/mantis/Assembler.py", line 17, in setup_databases
    mantis.setup_databases()
  File "/tools/miniconda3/envs/MANTIS-Annotation/lib/python3.9/site-packages/mantis/utils.py", line 588, in wrapper
    res = f(self, *args, **kwargs)
  File "/tools/miniconda3/envs/MANTIS-Annotation/lib/python3.9/site-packages/mantis/Database_generator.py", line 42, in setup_databases
    passed_tax_check=self.prepare_queue_setup_databases_tax()
  File "/tools/miniconda3/envs/MANTIS-Annotation/lib/python3.9/site-packages/mantis/Database_generator.py", line 136, in prepare_queue_setup_databases_tax
    self.download_and_unzip_eggnogdb()
  File "/tools/miniconda3/envs/MANTIS-Annotation/lib/python3.9/site-packages/mantis/Database_generator.py", line 853, in download_and_unzip_eggnogdb
    download_file(url, output_folder=self.mantis_paths['NOG'], stdout_file=stdout_file)
  File "/tools/miniconda3/envs/MANTIS-Annotation/lib/python3.9/site-packages/mantis/utils.py", line 725, in download_file
    raise Exception
Exception
~

**Comment by PedroMTQ** [comment]
Hello @jblakele 
I have tried to run this on my machine and the download seems to be working fine, could you please try to run the setup again but just with the NOG database?

Please change your MANTIS.cfg file so that the other databases are deactivated, like so:
pfam_ref_folder=NA
kofam_ref_folder=NA
tcdb_ref_folder=NA
ncbi_ref_folder=NA

Please make sure you have enough space in the folder you are downloading the data to (in your case `/tools/miniconda3/envs/MANTIS-Annotation/lib/python3.9/site-packages/References/NOG/`. The NOG database is quite large (couple hundred GBs).
