### ISSUE TITLE
Installation: Unsatisfiable error

### ISSUE THREAD

**Issue by susheelbhanu** [PedroMTQ/mantis#46]
Hey @PedroMTQ 

The current installation instructions might need to be updated. Pulling the tool using `conda install -c bioconda mantis_pfa` was throwing `Unsatisfiable errors`.

Replacing it with `conda install -c conda-forge -c bioconda mantis_pfa` seems to work.

Thanks!

**Comment by thh32** [comment]
Same issue and solution here

**Comment by PedroMTQ** [comment]
Thank you both, I've updated the readme.
